cookie:
  expiry_days: 7
  key: autovalidation
  name: autocookie
credentials:
  usernames:
    corp:
      email: test@test.kz
      failed_login_attempts: 0
      logged_in: false
      name: Corp User
      password: 8Y751q
    cvm:
      email: test@test.kz
      failed_login_attempts: 0
      logged_in: false
      name: CVM User
      password: nBM3y4
    roznica:
      email: test@test.kz
      failed_login_attempts: 0
      logged_in: false
      name: Roznica User
      password: tqXAIZ
    test:
      email: test@test.kz
      failed_login_attempts: 0
      logged_in: false
      name: Corp User
      password: test123
    validation:
      email: validation@bcc.kz
      failed_login_attempts: 0
      logged_in: false
      name: Valid User
      password: SOX3nM
pre-authorized:
  emails:
  - test@test.com
